### PR TITLE
Use Docker exec for all tooling jobs locally.

### PR DESCRIPTION
**Pull request by iHiD**
@ErikSchierboom This removes both the local setup and local-webserver. Everything runs "normally" through Docker. It works for me for Ruby. Could you test for you in C# please?

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@iHiD It doesn't seem to work me, not even for Ruby:

```
Starting ToolingInvoker::Worker...,
59163d91-f429-4440-9620-36839d613320: Starting job,
59163d91-f429-4440-9620-36839d613320: Invoking request: test-runner:ruby:lasagna,
59163d91-f429-4440-9620-36839d613320: Preparing input,
59163d91-f429-4440-9620-36839d613320: Invoking container,
59163d91-f429-4440-9620-36839d613320: Running docker container run -a stdout -a stderr --stop-timeout 0 --rm -v /tmp/exercism-tooling-jobs/59163d91-f429-4440-9620-36839d613320-5f58259cb8b8e205e5af45c36859119b/code:/mnt/exercism-iteration -l exercism-59163d91-f429-4440-9620-36839d613320-db962c1ae9de3ef8ad6d4953e3790d4d --network none -m 1GB /ruby-test-runner:production lasagna /mnt/exercism-iteration/ /mnt/exercism-iteration/,
#<Thread:0x000056506b690408@/usr/src/app/lib/tooling_invoker/exec_docker.rb:25 run> terminated with exception (report_on_exception is true):,
/usr/local/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - docker (Errno::ENOENT),
	from /usr/local/lib/ruby/2.6.0/open3.rb:213:in `popen_run',
	from /usr/local/lib/ruby/2.6.0/open3.rb:101:in `popen3',
	from /usr/src/app/lib/tooling_invoker/exec_docker.rb:68:in `exec_command!',
	from /usr/src/app/lib/tooling_invoker/exec_docker.rb:27:in `block in call',
59163d91-f429-4440-9620-36839d613320: Total time: 0.3050243854522705,
```

It complains of not being able to run Docker, which makes sense as the Docker container does not have docker installed. I could verify this by running:

```
erik@VELPIE:~/development-environment$ ./bin/shell tooling-invoker
{^_^} tooling-invoker
      /usr/src/app % docker
bash: docker: command not found
```

**Comment by ErikSchierboom** [comment]
If I then add ` RUN apk add docker` to the `dev.Dockerfile` file, rebuild the image and restart the container, I do have access to Docker. I then have to add the `- /var/run/docker.sock:/var/run/docker.sock` volume mapping in the development environment to actually be able to run Docker commands.

**Comment by ErikSchierboom** [comment]
If I submit a C# or Ruby solution, it does run the docker command, but there appears to be something amiss:

`fa3eafa2-b078-4b9b-8f86-302a480922b2: Running docker container run -a stdout -a stderr --stop-timeout 0 --rm -v /tmp/exercism-tooling-jobs/fa3eafa2-b078-4b9b-8f86-302a480922b2-904aafda06ce89333610540e1f5aef08/code:/mnt/exercism-iteration -l exercism-fa3eafa2-b078-4b9b-8f86-302a480922b2-bbc63054cfcb51414aa72493656ad9ee --network none -m 3GB /csharp-test-runner:production lucians-luscious-lasagna /mnt/exercism-iteration/ /mnt/exercism-iteration/`

The image it tries to run is `/csharp-test-runner:production`, so it looks like `tooling_ecr_repository_url` is not set. I've hardcoded the image to `exercism/csharp-test-runner` to workaround this.

I then see that the following command is executed:

`docker container run -a stdout -a stderr --stop-timeout 0 --rm -v /tmp/exercism-tooling-jobs/861e4382-9285-4d4d-99bc-91576c41657c-d0760492ee22233e99b5bd423140bf00/code:/mnt/exercism-iteration -l exercism-861e4382-9285-4d4d-99bc-91576c41657c-3ea6e28ff0e397ee30b013027dc93847 --network none -m 3GB exercism/csharp-test-runner lucians-luscious-lasagna /mnt/exercism-iteration/ /mnt/exercism-iteration/`

If I shell into the `tooling-invoker` machine and run this command, I get:

```
{^_^} tooling-invoker
      /usr/src/app % docker container run -a stdout -a stderr --stop-timeout 0 --rm -v /tmp/exercism-tooling-jobs/861e4382-9285-4d4d-99bc-91576c41657c-d0760492ee22233e99b5bd423140bf00/code:/mnt/exercism-iteration -l exercism-861e4382-9285-4d4d-99bc-91576c41657c-3ea6e28ff0e397ee30b013027dc93847 --network none -m 3GB exercism/csharp-test-runner lucians-luscious-lasagna /mnt/exercism-iteration/ /mnt/exercism-iteration/
[2020-11-26 11:08:11Z] Running test runner for 'lucians-luscious-lasagna' solution...
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/mnt/exercism-iteration/LuciansLusciousLasagnaTests.cs'.
File name: '/mnt/exercism-iteration/LuciansLusciousLasagnaTests.cs'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Exercism.TestRunner.CSharp.TestSuite.FromOptions(Options options) in /app/TestSuite.cs:line 50
   at Exercism.TestRunner.CSharp.Program.CreateTestResults(Options options) in /app/Program.cs:line 18
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Exercism.TestRunner.CSharp.Program.Main(String[] args) in /app/Program.cs:line 10
Aborted
```

So it looks like the file cannot be found. Let's check this by shell out into the test runner:

`docker container run -it --entrypoint /bin/sh --rm -v /tmp/exercism-tooling-jobs/861e4382-9285-4d4d-99bc-91576c41657c-d0760492ee22233e99b5bd423140bf00/code:/mnt/exercism-iteration -l exercism-861e4382-9285-4d4d-99bc-91576c41657c-3ea6e28ff0e397ee30b013027dc93847 --network none -m 3GB exercism/csharp-test-runner`

Now let's check the contents of `/mnt/exercism-iteration`:

```
/opt/test-runner # ls -al /mnt/exercism-iteration
total 8
drwxr-xr-x    2 root     root          4096 Nov 26 11:07 .
drwxr-xr-x    1 root     root          4096 Nov 26 11:10 ..
```

Hmmm, does indeed look like its empty. This appears to be making sense somehow, as the Docker executable is actually running on the host, and thus the volumes mappings it can access should be the host's (see https://stackoverflow.com/questions/49312100/docker-in-docker-volumes-not-working-full-of-files-in-1st-level-container-em). The path to the volume that should be used must then be relative to the host. Let's verify this by running:

```
docker container run -it --entrypoint /bin/sh --rm --mount type=bind,src=/home/erik/tooling-invoker,dst=/invoker  -l exercism-861e4382-9285-4d4d-99bc-91576c41657c-3ea6e28ff0e397ee30b013027dc93847 --network none -m 3GB exercism/csharp-test-runner
/opt/test-runner # ls -al /invoker
total 140
drwxr-xr-x    9 1000     1000          4096 Nov 26 09:36 .
drwxr-xr-x    1 root     root          4096 Nov 26 11:17 ..
drwxr-xr-x    8 1000     1000          4096 Nov 26 09:36 .git
-rw-r--r--    1 1000     1000           118 Nov 13 11:56 .gitattributes
drwxr-xr-x    3 1000     1000          4096 Nov 13 11:56 .github
-rw-r--r--    1 1000     1000            63 Nov 13 11:56 .gitignore
-rw-r--r--    1 1000     1000          1322 Nov 13 11:56 .rubocop.yml
-rw-r--r--    1 1000     1000            11 Nov 13 11:56 .ruby-version
-rw-r--r--    1 1000     1000           493 Nov 17 15:23 Gemfile
-rw-r--r--    1 1000     1000          2359 Nov 17 15:23 Gemfile.lock
-rw-r--r--    1 1000     1000         34523 Nov 13 11:56 LICENSE
-rw-r--r--    1 1000     1000          2095 Nov 13 11:56 README.md
-rw-r--r--    1 1000     1000           187 Nov 13 11:56 Rakefile
drwxr-xr-x    2 1000     1000          4096 Nov 17 15:35 bin
-rw-r--r--    1 1000     1000           633 Nov 26 11:03 dev.Dockerfile
drwxr-xr-x    3 1000     1000          4096 Nov 17 15:23 lib
drwxr-xr-x   74 1000     1000          4096 Nov 17 15:53 node_modules
-rw-r--r--    1 1000     1000           215 Nov 13 11:56 package.json
drwxr-xr-x    3 1000     1000          4096 Nov 13 11:56 scripts
drwxr-xr-x    5 1000     1000          4096 Nov 26 09:36 test
-rw-r--r--    1 1000     1000           310 Nov 26 09:36 tools.json
-rw-r--r--    1 1000     1000         23579 Nov 13 11:56 yarn.lock
```

And indeed, this works! We do need to mount the volume mount that contains the exercise, so let's try that:

```
docker container run -it --entrypoint /bin/sh --rm --mount type=volume,src=tmp,dst=/mounted-tmp  -l exercism-861e4382-9285-4d4d-99bc-91576c41657c-3ea6e28ff0e397ee30b013027dc93847 --network none -m 3GB exercism/csharp-test-runner
ls -al /mounted-tmp
total 8
drwxr-xr-x    2 root     root          4096 Nov 26 10:46 .
drwxr-xr-x    1 root     root          4096 Nov 26 11:22 ..
```

Hmmm, that does not seem to work.

**Comment by ErikSchierboom** [comment]
I'm gonna try some other alternatives.

**Comment by iHiD** [comment]
Hmmm, ok. So this works fine outside of the dev-env setup. I hadn't realised the docker-in-docker thing would hurt us. That makes sense though. Lets chat when you're back on about it :)

**Pull request merged**
